### ISSUE TITLE
Relationship to other repositories

### ISSUE THREAD

**Issue by cthoyt** [linkml/prefixmaps#6]
Several repositories (and I'm sure more than the following) do similar things in hosting contexts/prefix maps/JSON-LD (whatever the name):

- https://github.com/prefixcommons/biocontext
- https://github.com/prefixcommons/prefixcommons-py

Now that this is another one, how can these all be coalesced? Can they be deprecated, their READMEs updated and pointed here, then turned to archive only? Otherwise people might continue to discover them even as they're out of date.

**Comment by cthoyt** [comment]
@hrshdhgd bump, there's still lots of confusion as to why there are so many packages that seem to do the same thing

**Comment by cmungall** [comment]
biocontext and prefixcommons-py will be deprecated.
